apiVersion: v1
kind: ImageStream
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      openshift.io/display-name: MySQL Image Stream
      description: >-
        PetClinic MySQL server Image Stream.
    from:
      kind: DockerImage
      name: mysql
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
