apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: petclinic
  name: petclinic
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: petclinic
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
