apiVersion: v1
kind: BuildConfig
metadata:
  name: pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent none
          stages {
            stage("Create Project Environment") {
              agent {label 'maven'}
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/master"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'environment']
                                ],
                                userRemoteConfigs: [[url: "https://bitbucket.org/stevshil/petclinicmysqlopenshift"]]
                            ])
                  }
                }
                stage("Create/Update Database Deployment Config") {
                  steps {
                    dir('environment/jenkins-Openshift/ymls') {
                      sh 'oc apply -f mysql-deploymentconfig.yaml'
                      sh 'oc apply -f mysql-imagestream.yaml'
                      sh 'oc apply -f mysql-service.yaml'
                    }
                  }
                }
                stage("Create/Update PetClinic Deployment Config") {
                  steps {
                    dir('environment/jenkins-Openshift/ymls') {
                      sh 'oc apply -f petclinic-deploymentconfig.yaml'
                      sh 'oc apply -f petclinic-imagestream.yaml'
                      sh 'oc apply -f petclinic-service.yaml'
                      sh 'oc expose service petclinic --hostname=pc.appsrv.tps.local || echo "PetClinic already available to web"'
                    }
                  }
                }
              }
            }
            stage("Build PetClinic") {
              agent {label 'maven'}
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/master"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'petclinic']
                                ],
                                userRemoteConfigs: [[url: "https://bitbucket.org/stevshil/petclinicmysqlopenshift"]]
                            ])
                  }
                }
                stage("Build JAR") {
                  steps {
                    dir('petclinic') {
                      sh 'mvn -Dmaven.test.skip=true clean package'
                    }
                  }
                }
                stage("Create Build For Petclinic") {
                  steps {
                    dir('petclinic') {
                      sh 'oc new-build --strategy docker --binary --name petclinic || echo "Build already exists"'
                    }
                  }
                }
                stage("Build PetClinic Image") {
                  steps {
                    dir('petclinic') {
                      sh 'ln Dockerfile-petclinic Dockerfile'
                      sh 'oc start-build petclinic --follow --wait=true --from-dir .|| (echo "PetClinic BUILD FAILED" && exit 1)'
                      sh 'rm Dockerfile'
                    }
                  }
                }
              }
            }
            stage("Build Database") {
              agent {label 'maven'}
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/master"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'database']
                                ],
                                userRemoteConfigs: [[url: "https://bitbucket.org/stevshil/petclinicmysqlopenshift"]]
                            ])
                  }
                }
                stage("Create Build For Database Server") {
                  steps {
                    dir('database') {
                      sh 'oc new-build --strategy docker --binary --name mysql || echo "Build already exists"'
                    }
                  }
                }
                stage("Build Database Image") {
                  steps {
                    dir('database') {
                      sh 'ln Dockerfile-mysql Dockerfile'
                      sh 'oc start-build mysql --follow --wait=true --from-dir .|| (echo "DB BUILD FAILED" && exit 1)'
                      sh 'rm Dockerfile'
                    }
                  }
                }
              }
            }
            stage("Deploy Application") {
              agent {label 'maven'}
              stages {
                stage("Deploy Database") {
                  steps {
                    sh 'oc deploy --latest dc/mysql || echo "Database already deployed"'
                  }
                }
                stage("Deploy Petclinic") {
                  steps {
                    sh 'oc deploy --latest dc/petclinic || echo "Petclinic already deployed"'
                  }
                }
              }
            }
            stage("Test Application") {
              agent {label 'maven'}
              when {
                not { environment name: 'GITREPOTEST', value: 'false' }
              }
              stages {
                stage("Clone Source") {
                  steps {
                    checkout([$class: 'GitSCM',
                                branches: [[name: "*/master"]],
                                extensions: [
                                  [$class: 'RelativeTargetDirectory', relativeTargetDir: 'tests']
                                ],
                                userRemoteConfigs: [[url: "https://bitbucket.org/stevshil/petclinicmysqlopenshift"]]
                            ])
                  }
                }
                stage("Test environment") {
                  steps {
                    dir('tests') {
                      sh 'echo "You should perform tests to make sure your application works"'
                      sh 'echo "Something like a curl to a status port -  curl http://myapp.oc.local/trades/status"'
                      sh 'echo "Or http://myapp.oc.local/trades/list"'
                    }
                  }
                }
              }
            }
          }
        }
    type: JenkinsPipeline
    triggers: {
      pollSCM('H */2 * * 1-5')
    }
